MODE: 'val'  # 'train', 'val' or 'test

DATA:
  NAME: 'scannet_depth_rnn'
  PATH: 'F:/D/ScanNetv1'
  TUPLE_PATH: "data_splits/ScanNetv1/"
#  TUPLE_PATH: "data_splits/ScanNetv1-Pre/"
#  TUPLE_FILE: 'train_views_3510.txt'
#  TUPLE_FILE: 'train_2.txt'
  BATCH_SIZE: 24
  N_WORKERS: 4
  N_VIEWS: 8

TEST:
  MIN_DEPTH: 0.25
  MAX_DEPTH: 5.0
