LOGDIR: './checkpoints'
SAVE_FREQ: 1
#RESUME: True
MODE: 'train'

DATA:
  NAME: 'scannet_depth_rnn'
  PATH: 'F:/D/ScanNetv1'
  TUPLE_PATH: "data_splits/ScanNetv1/"
#  TUPLE_PATH: "data_splits/ScanNetv1-Pre/"
#  TUPLE_FILE: 'train_views_035.txt'
  BATCH_SIZE: 24
  N_WORKERS: 4
  N_VIEWS: 8
  LOAD_IMG: True
#  LOAD_IMG: False


TRAIN:
  EPOCHS: 30
  LR: 1e-3
#  LREPOCHS: '12,24,48,52,56,60:2'
  LREPOCHS: '18,24,26,28:2'
#  LREPOCHS: '10,14,16,18:2'


MODEL:
  BACKBONE2D:
    ARC: 'fpn-mnas-1'